### PR TITLE
Added Versioning to enable building via Yocto

### PR DESCRIPTION
**Pull request by matt2005**
Added versioning to enable building via Yocto

### CODE REVIEW

**Comment by rsjudka** [comment]
any specific reason the version was chosen as 2.1.0?

**Comment by matt2005** [comment]
i thought about 0.0.1 but didn't want it to clash with others as being the first version. I can change it  just really needed something to test that it would worked. I thought 2.1 based on 2021, but that's about it.

**Comment by rsjudka** [comment]
soungs good to me!

question tho, because I'm much less familiar with that... will there ever be a time where aasdk_proto lib will need a different version than aasdk lib?

**Comment by matt2005** [comment]
I don't think there will be a need for different versions, however there is more chance of someone forgetting to increase the version number if they are separate.

**Pull request merged**
